### PR TITLE
:art: Add Android support

### PR DESCRIPTION
**Pull request by PatriceVignola**
I added support for Android via a native bridge with jpct-ae. This includes:

- Java code to render the view and render the model via jpct-ae
- Custom .model loader for Android to load demon.model
- The Android version of the example app

There's a [known bug](https://github.com/facebook/react-native/issues/7221) where the Android gesture responder's touch location doesn't update. Thereforce, the GestureResponder example doesn't work for Android. We could make a workaround by calculating the delta ourselves, but I think it's better to just update the react-native version since it's probably fixed in the latest version.

### CODE REVIEW

**Comment by PatriceVignola** [comment]
This looks like a big commit, but most of it were generated when creating the new Android projects.

**Comment by PatriceVignola** [comment]
Haha, I like computer graphics, but I had never seen the .model format before so I was curious :)

**Comment by rastapasta** [comment]
Such. Well. Work!
Catching up with code after the new years, tackling the RN update, fixing the touch responder and featuring you in the readme are the next items on my model-view queue :)

Thanks again for this amazing contribution + welcome on board!

**Comment by PatriceVignola** [comment]
It was my pleasure, glad I could help :) Thanks for the karma treasure trove and happy new year!

**Pull request merged**
